### PR TITLE
Update 0000-01-01-Herefordshire.md

### PR DESCRIPTION
**Pull request by joolsr**
I've checked the info, everything is still as before. I've updated last updated so at least it shows we're still (just about) still going

### CODE REVIEW

**Comment by joolsr** [comment]
all ok, just wanted to make herefordshire show that details last checked recently

**Comment by gwestwood** [comment]
Thanks for that @joolsr.  Yes, that's a good idea.  We should do that for every LUG that responds.

**Comment by gwestwood** [comment]
@joolsr - Sorry, I've just checked the URL ( [http://www.herefordshire.lug.org.uk](http://www.herefordshire.lug.org.uk) ) and it's going to a default Apache page - can you confirm that is the correct URL and if the DNS entry at lug.org.uk is incorrect, please email us the new IP/CNAME at the admin@lug.org.uk address?  Thanks.

**Comment by gwestwood** [comment]
This has now been merged.

**Pull request merged**
