### PR TITLE
Turn "Status" into a dropdown, filter records accordingly

### LINKED ISSUE #156: Suggestion: Filter out inactive LUGs from the list of LUGs and have them on a separate page
Filter out LUGs set as Inactive from the page at https://lug.org.uk/lugs/ and have them listed on a separate page for inactive LUGs.

### PR DESCRIPTION
**Pull request by JonTheNiceGuy**
Closes #156

### CODE REVIEW

**Comment by gwestwood** [comment]
Thanks Jon.  Looks good to me.  Are we able to try it on the testsite URL?

**Review by gwestwood — COMMENTED** [review]
Thanks Jon. Looks good to me. Are we able to try it on the testsite URL before we merge it?

**Comment by JonTheNiceGuy** [comment]
Done. We'll need to checkout `master` once you're happy with the content :)

**Comment by JonTheNiceGuy** [comment]
Note that https points to the oldsite for some reason, not the test... which is odd.

**Comment by gwestwood** [comment]
Yeap, that seems to work well.  My only suggestion is that the filter default to 'Active' so visitors are initially shown the active LUGs.

**Comment by JonTheNiceGuy** [comment]
OK, testsite updated with latest version. This now pre-filters to "Active". Note that this *does* mean that the row-highlighting is a bit weird (you might have two rows with the same colour, as the "Inactive" row has been filtered out).

**Review by gwestwood — APPROVED** [review]
I'm happy with this. :-)

**Pull request merged**
